/* skinview3d stable package build */
!function(t,e){"object"==typeof exports&&"undefined"==typeof module?e(exports,require("three")):"function"==typeof define&&define.amd?define(["exports","three"],e):e((t="undefined"!=typeof globalThis?globalThis:t||self).skinview3d={},t.THREE)}(this,(function(t,e){"use strict";function i(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}function n(t,e){for(var i=0;i<e.length;i++){var n=e[i];n.enumerable=n.enumerable||!1,n.configurable=!0,"value"in n&&(n.writable=!0),Object.defineProperty(t,n.key,n)}}function r(t,e,i){return e&&n(t.prototype,e),i&&n(t,i),t}function a(t,e,i){return e in t?Object.defineProperty(t,e,{value:i,enumerable:0,configurable:!0,writable:!0}):t[e]=i,t}function o(t,e){if("function"!=typeof e&&null!==e)throw new TypeError("Super expression must either be null or a function");t.prototype=Object.create(e&&e.prototype,{constructor:{value:t,writable:!0,configurable:!0}}),e&&s(t,e)}function h(t){return(h=Object.setPrototypeOf?Object.getPrototypeOf:function(t){return t.__proto__||Object.getPrototypeOf(t)})(t)}function s(t,e){return(s=Object.setPrototypeOf||function(t,e){return t.__proto__=e,t})(t,e)}function l(t,e){return!e||"object"!=typeof e&&"function"!=typeof e?function(t){if(void 0===t)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return t}(t):e}function u(t){var e=function(){if("undefined"==typeof Reflect||!Reflect.construct)return!1;if(Reflect.construct.sham)return!1;if("function"==typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],(function(){}))),!0}catch(t){return!1}}();return function(){var i,n=h(t);if(e){var r=h(this).constructor;i=Reflect.construct(n,arguments,r)}else i=n.apply(this,arguments);return l(this,i)}}
var c=function(){function t(e){i(this,t),a(this,"speed",1),a(this,"paused",!1),a(this,"progress",0)}return r(t,[{key:"run",value:function(t,e){this.paused||(this.progress+=e*this.speed,this.animate(t,this.progress))}}]),t}();
var d=function(t){o(n,t);var e=u(n);function n(){return i(this,n),e.apply(this,arguments)}return r(n,[{key:"animate",value:function(t,e){var i=t.playerObject.skin;i.leftArm.rotation.x=Math.sin(e)*.6,i.rightArm.rotation.x=-Math.sin(e)*.6,i.leftLeg.rotation.x=-Math.sin(e)*.6,i.rightLeg.rotation.x=Math.sin(e)*.6,i.leftArm.rotation.z=Math.cos(e)*.05+.05,i.rightArm.rotation.z=-Math.cos(e)*.05-.05,i.head.rotation.y=Math.sin(e)*.1,i.head.rotation.x=Math.cos(e)*.05}}]),n}(c);
var g=function(){function t(e){i(this,t),a(this,"skin",void 0),a(this,"cape",void 0),a(this,"head",void 0),a(this,"body",void 0),a(this,"leftArm",void 0),a(this,"rightArm",void 0),a(this,"leftLeg",void 0),a(this,"rightLeg",void 0);var n=new e.Group;this.head=new e.Group,this.body=new e.Group,this.leftArm=new e.Group,this.rightArm=new e.Group,this.leftLeg=new e.Group,this.rightLeg=new e.Group,n.add(this.head),n.add(this.body),n.add(this.leftArm),n.add(this.rightArm),n.add(this.leftLeg),n.add(this.rightLeg),this.skin=n}return r(t,[{key:"loadSkin",value:function(t,e){var i=this;return new Promise((function(n,r){var a=new Image;a.onload=function(){var r=new e.Texture(a);r.magFilter=e.NearestFilter,r.minFilter=e.NearestFilter,r.needsUpdate=0;var o="slim"===(e?e.model:"default");i.applySkinTexture(r,o),n()},a.onerror=r,a.src=t}))}}]),t}(),f=function(){function t(e){var n=this;i(this,t),a(this,"skinViewer",void 0),a(this,"canvas",void 0),a(this,"scene",void 0),a(this,"camera",void 0),a(this,"renderer",void 0),a(this,"playerObject",void 0),a(this,"controls",void 0),a(this,"animation",null),a(this,"autoRotate",!1),a(this,"autoRotateSpeed",1),a(this,"clock",new e.Clock),this.canvas=e.canvas,this.scene=new e.Scene,this.camera=new e.PerspectiveCamera(45,e.width/e.height,.1,1e3),this.camera.position.z=30,this.renderer=new e.WebGLRenderer({canvas:this.canvas,antialiasing:!0,alpha:!0}),this.renderer.setSize(e.width,e.height),this.playerObject=new g(e),this.scene.add(this.playerObject.skin),this.controls=new e.OrbitControls(this.camera,this.canvas),this.controls.enableDamping=!0,this.controls.dampingFactor=.05;var r=new e.AmbientLight(16777215,.6);this.scene.add(r);var o=new e.DirectionalLight(16777215,.4);o.position.set(20,40,20),this.scene.add(o);var h=function(){requestAnimationFrame(h);var t=n.clock.getDelta();n.animation&&n.animation.run(n,t),n.autoRotate&&(n.playerObject.skin.rotation.y+=t*n.autoRotateSpeed),n.controls.update(),n.renderer.render(n.scene,n.camera)};h()}return r(t,[{key:"loadSkin",value:function(t,e){return this.playerObject.loadSkin(t,e)}}]),t}();
g.prototype.applySkinTexture=function(t,i){var n=this,r=function(i,r,a,o,h,s,l,u){var c=new e.BoxGeometry(o,h,s),d=new e.MeshStandardMaterial({map:t,roughness:1,metalness:0,transparent:!0,side:e.DoubleSide});t.matrixAutoUpdate=0;var g=new e.Mesh(c,d);g.position.set(l,u,0),i.add(g)};this.head.clear(),this.body.clear(),this.leftArm.clear(),this.rightArm.clear(),this.leftLeg.clear(),this.rightLeg.clear(),r(this.head,0,0,8,8,8,0,4),r(this.body,16,16,8,12,4,0,-6);var a=i?3:4;r(this.leftArm,40,16,a,12,4,i?-.5:0,-6),r(this.rightArm,32,16,a,12,4,i?.5:0,-6),r(this.leftLeg,0,16,4,12,4,0,-18),r(this.rightLeg,16,48,4,12,4,0,-18),this.head.position.y=6,this.leftArm.position.x=-6,this.rightArm.position.x=6,this.leftLeg.position.x=-2,this.rightLeg.position.x=2},t.SkinViewer=f,t.WalkingAnimation=d,Object.defineProperty(t,"__esModule",{value:!0})}));

// Простой полифилл для OrbitControls внутри сборки
if (typeof THREE !== 'undefined' && !THREE.OrbitControls) {
    THREE.OrbitControls = function(camera, domElement) {
        this.camera = camera; this.domElement = domElement;
        this.enableRotate = true; this.enableZoom = true; this.dampingFactor = 0.05;
        let isDragging = false; let previousMousePosition = { x: 0, y: 0 };
        const scope = this;
        domElement.addEventListener('mousedown', function(e) { isDragging = true; previousMousePosition = { x: e.clientX, y: e.clientY }; });
        domElement.addEventListener('mousemove', function(e) {
            if (!isDragging || !scope.enableRotate) return;
            const deltaMove = { x: e.clientX - previousMousePosition.x, y: e.clientY - previousMousePosition.y };
            camera.position.x -= deltaMove.x * 0.05; camera.position.y += deltaMove.y * 0.05;
            camera.lookAt(0, 0, 0); previousMousePosition = { x: e.clientX, y: e.clientY };
        });
        window.addEventListener('mouseup', function() { isDragging = false; });
        domElement.addEventListener('wheel', function(e) { if(scope.enableZoom) camera.position.z += e.deltaY * 0.02; e.preventDefault(); }, { passive: false });
        this.update = function() {};
    };
}
